POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name": "stephen",
    "goals" : "633ef3cbb3755c8a988ae056"
}

###
GET http://localhost:3000/users HTTP/1.1

###
GET http://localhost:3000/users/goals HTTP/1.1


###
POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json

{
    "title": "TASK_01",
    "type": "TYPE_01",
    "user":  "633ef3e3b3755c8a988ae05b"
}

###
GET http://localhost:3000/tasks HTTP/1.1


###
POST http://localhost:3000/goals HTTP/1.1
content-type: application/json

{
    "title": "GOAL_01",
    "type": "GOAL_01",
    "user":  "633ef3e3b3755c8a988ae05b"
}

###
GET http://localhost:3000/goals HTTP/1.1
